### ISSUE TITLE
Bug: Editing a recipe in favorites breaks the details link

### ISSUE THREAD

**Issue by axeberg** [chas-academy/06-recipe-app-frontend-tolgakoyluoglu#2]
**Steps to reproduce:**

0. Log in as registered user (axel.olsson@chasacademy.se | test1234)
1. Click any recipe in the search results.
2. Click "Add to Favorites" button.
3. Click "My recipes" navigation item in the header.
4. Input text after the original title of the recipe:
![image](https://user-images.githubusercontent.com/343422/54677018-546da380-4b02-11e9-9be2-dd81ab8f6325.png)
5. Click "Save Changes"
6. Click "Details".

**Expected result:**
To be shown the detail view of the recipe.

**Actual result:**
![image](https://user-images.githubusercontent.com/343422/54677098-8121bb00-4b02-11e9-93af-38a3e10167a1.png)

The request that is fired when navigating looks like this:
https://api.edamam.com/search?q=Too-Tasty-to-Be-Good-for-You%20Cauliflower%20Mac%20%E2%80%98n%20Cheese%20[TEST]&app_id=4e1fec26&app_key=700a8df20bec59685c5284880e20ef03&from=0&to=1

Which I'm assuming isn't a valid recipe, which breaks the UI.

**Comment by tolgakoyluoglu** [comment]
Done
