### ISSUE TITLE
Bug: "Add To Favorites" button still clickable after recipe added to favorites

### ISSUE THREAD

**Issue by axeberg** [chas-academy/06-recipe-app-frontend-tolgakoyluoglu#3]
Since I only have one list of favorites I can't really add a recipe more than once, so if a recipe exists in my favorites - I think the button should not be clickable after the first time. Or, if the recipe _is_ in my favorites the button should change from "Add To Favorites" to "Remove From Favorites".

**Comment by tolgakoyluoglu** [comment]
Done
