### ISSUE TITLE
Bug: Filter dropdowns not working as expected

### ISSUE THREAD

**Issue by axeberg** [chas-academy/06-recipe-app-frontend-tolgakoyluoglu#4]
**Steps to reproduce**:

1. Log in as user (axel.olsson@chasacademy.se | test1234)
2. Type in "Pasta" in the search bar.
3. Select "Vegan" in the leftmost filter dropdown with the label "Allergies". (btw being vegan isn't an allergy...)
4. Press "Get Recipes" button.

**Expected results**:
> "As a user I would like to be able to search for recipes by dietary preference, e.g. vegan/vegetarian/lacto-ovo and so on, and get recipe results based on those preferences."

When I select a filter value I expect the results to be filtered based on that.

**Actual results**:
The user gets non-vegan results back from the search:
![pasta-search-vegan](https://user-images.githubusercontent.com/343422/54677827-035eaf00-4b04-11e9-9f30-07a81190d1cf.jpg)

**Comment by tolgakoyluoglu** [comment]
Done
